# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'Starting Docker build'
  displayName: 'Starting Docker build'

- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    containerRegistry: 'acrconnection'
    command: 'login'
- task: Docker@2
  displayName: 'Build and Push Frontend Img'
  inputs:
    containerRegistry: 'acrconnection'
    repository: 'frontend'
    command: 'buildAndPush'
    Dockerfile: './fullstackapp/frontend/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Build and Push Backend Img'
  inputs:
    containerRegistry: 'acrconnection'
    repository: 'backend'
    command: 'buildAndPush'
    Dockerfile: './fullstackapp/backend/Dockerfile'
    tags: 'latest'


- task: Kubernetes@1
  displayName: 'Deploy Backend to Kubernetes'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aksconnection'
    command: 'apply'
    useConfigurationFile: true
    configuration: './fullstackapp/kubernetes/backend.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'azuresubscriptionconnection'
    azureContainerRegistry: 'k8sdeployment.azurecr.io'

- task: Kubernetes@1
  displayName: 'Deploy Frontend to Kubernetes'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aksconnection'
    command: 'apply'
    useConfigurationFile: true
    configuration: './fullstackapp/kubernetes/frontend.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'azuresubscriptionconnection'
    azureContainerRegistry: 'k8sdeployment.azurecr.io'

  
- task: Kubernetes@1
  displayName: 'Deploy Database to Kubernetes'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aksconnection'
    command: 'apply'
    useConfigurationFile: true
    configuration: './fullstackapp/kubernetes/database.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
